### ISSUE TITLE
Don't show markdown icon in markdown preview

### ISSUE THREAD

**Issue by ghost** [manuelbieh/logo-file-icons#2]
**Why don't you show markdown icon in markdown preview ?**

![screenshot 2](https://cloud.githubusercontent.com/assets/16760489/14490672/5312d43e-019e-11e6-99fa-929fe0383f09.png)

**Comment by DavidBernal** [comment]
I think this is because the extension is "Preview"

**Comment by manuelbieh** [comment]
Should work now

**Comment by ghost** [comment]
:+1:
