### ISSUE TITLE
How creat Setting icon?

### ISSUE THREAD

**Issue by ghost** [manuelbieh/logo-file-icons#6]
@manuelbieh Can you creat Setting icon?

![screenshot 2](https://cloud.githubusercontent.com/assets/16760489/16651566/f7486a60-446e-11e6-8f9b-fe2e4817d89d.png)

**Comment by manuelbieh** [comment]
Re-added it in 1.1.8. I had overwritten/removed it by mistake.

**Comment by manuelbieh** [comment]
by the way: nice UI theme. What's the name of it? :)

**Comment by ghost** [comment]
It is [accents-ui](https://atom.io/themes/accents-ui)! You can try.

**Comment by ghost** [comment]
@manuelbieh I used your package and this is [Marvis UI](https://github.com/torn4dom4n/marvis-ui).
